package reinders.mike.StackRemoverTool.ReferenceMapping;

import java.util.HashMap;
import java.util.Map;

public class MTSStackingMod implements MappingInterface {

    private static Map<String, String> referenceMapping = new HashMap<>();

    static {
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedBullet.PrimalItemAmmo_AdvancedBullet_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_AdvancedBullet_Child.PrimalItemAmmo_AdvancedBullet_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedSniperBullet.PrimalItemAmmo_AdvancedSniperBullet_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_AdvancedSniperBullet_Child.PrimalItemAmmo_AdvancedSniperBullet_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AggroTranqDart.PrimalItemAmmo_AggroTranqDart_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_AggroTranqDart_Child.PrimalItemAmmo_AggroTranqDart_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowFlame.PrimalItemAmmo_ArrowFlame_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_ArrowFlame_Child.PrimalItemAmmo_ArrowFlame_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowStone.PrimalItemAmmo_ArrowStone_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_ArrowStone_Child.PrimalItemAmmo_ArrowStone_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowTranq.PrimalItemAmmo_ArrowTranq_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_ArrowTranq_Child.PrimalItemAmmo_ArrowTranq_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_BallistaArrow.PrimalItemAmmo_BallistaArrow_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_BallistaArrow_Child.PrimalItemAmmo_BallistaArrow_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_CompoundBowArrow.PrimalItemAmmo_CompoundBowArrow_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_CompoundBowArrow_Child.PrimalItemAmmo_CompoundBowArrow_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/WeaponFlamethrower/PrimalItemAmmo_Flamethrower.PrimalItemAmmo_Flamethrower_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_Flamethrower_Child.PrimalItemAmmo_Flamethrower_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_GrapplingHook.PrimalItemAmmo_GrapplingHook_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_GrapplingHook_Child.PrimalItemAmmo_GrapplingHook_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_RefinedTranqDart.PrimalItemAmmo_RefinedTranqDart_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_RefinedTranqDart_Child.PrimalItemAmmo_RefinedTranqDart_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/WeaponHomingMissile/PrimalItemAmmo_RocketHomingMissile.PrimalItemAmmo_RocketHomingMissile_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_RocketHomingMissile_Child.PrimalItemAmmo_RocketHomingMissile_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Rocket.PrimalItemAmmo_Rocket_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_Rocket_Child.PrimalItemAmmo_Rocket_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleBullet.PrimalItemAmmo_SimpleBullet_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_SimpleBullet_Child.PrimalItemAmmo_SimpleBullet_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleRifleBullet.PrimalItemAmmo_SimpleRifleBullet_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_SimpleRifleBullet_Child.PrimalItemAmmo_SimpleRifleBullet_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleShotgunBullet.PrimalItemAmmo_SimpleShotgunBullet_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_SimpleShotgunBullet_Child.PrimalItemAmmo_SimpleShotgunBullet_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqDart.PrimalItemAmmo_TranqDart_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_TranqDart_Child.PrimalItemAmmo_TranqDart_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqSpearBolt.PrimalItemAmmo_TranqSpearBolt_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemAmmo_TranqSpearBolt_Child.PrimalItemAmmo_TranqSpearBolt_Child_C");
        referenceMapping.put("/Game/PrimalEarth/Test/PrimalItemC4Ammo.PrimalItemC4Ammo_C", "/Game/Mods/Stack500_50/Ammo/PrimalItemC4Ammo_Child.PrimalItemC4Ammo_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Amarberry.PrimalItemConsumable_Berry_Amarberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Amarberry_Child.PrimalItemConsumable_Berry_Amarberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Azulberry.PrimalItemConsumable_Berry_Azulberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Azulberry_Child.PrimalItemConsumable_Berry_Azulberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Mejoberry.PrimalItemConsumable_Berry_Mejoberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Mejoberry_Child.PrimalItemConsumable_Berry_Mejoberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Narcoberry.PrimalItemConsumable_Berry_Narcoberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Narcoberry_Child.PrimalItemConsumable_Berry_Narcoberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Stimberry.PrimalItemConsumable_Berry_Stimberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Stimberry_Child.PrimalItemConsumable_Berry_Stimberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Tintoberry.PrimalItemConsumable_Berry_Tintoberry_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Berry_Tintoberry_Child.PrimalItemConsumable_Berry_Tintoberry_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BugRepellant.PrimalItemConsumable_BugRepellant_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_BugRepellant_Child.PrimalItemConsumable_BugRepellant_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Consumables/PrimalItemConsumable_CactusSap.PrimalItemConsumable_CactusSap_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CactusSap_Child.PrimalItemConsumable_CactusSap_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedLambChop.PrimalItemConsumable_CookedLambChop_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedLambChop_Child.PrimalItemConsumable_CookedLambChop_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat.PrimalItemConsumable_CookedMeat_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedMeat_Child.PrimalItemConsumable_CookedMeat_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Fish.PrimalItemConsumable_CookedMeat_Fish_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedMeat_Fish_Child.PrimalItemConsumable_CookedMeat_Fish_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Jerky.PrimalItemConsumable_CookedMeat_Jerky_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedMeat_Jerky_Child.PrimalItemConsumable_CookedMeat_Jerky_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat.PrimalItemConsumable_CookedPrimeMeat_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedPrimeMeat_Child.PrimalItemConsumable_CookedPrimeMeat_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Fish.PrimalItemConsumable_CookedPrimeMeat_Fish_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedPrimeMeat_Fish_Child.PrimalItemConsumable_CookedPrimeMeat_Fish_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Jerky.PrimalItemConsumable_CookedPrimeMeat_Jerky_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_CookedPrimeMeat_Jerky_Child.PrimalItemConsumable_CookedPrimeMeat_Jerky_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Honey.PrimalItemConsumable_Honey_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Honey_Child.PrimalItemConsumable_Honey_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_JellyVenom.PrimalItemConsumable_JellyVenom_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_JellyVenom_Child.PrimalItemConsumable_JellyVenom_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Aquatic.PrimalItemConsumable_Mushroom_Aquatic_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Mushroom_Aquatic_Child.PrimalItemConsumable_Mushroom_Aquatic_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Ascerbic.PrimalItemConsumable_Mushroom_Ascerbic_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Mushroom_Ascerbic_Child.PrimalItemConsumable_Mushroom_Ascerbic_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Auric.PrimalItemConsumable_Mushroom_Auric_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Mushroom_Auric_Child.PrimalItemConsumable_Mushroom_Auric_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemConsumable_NamelessVenom.PrimalItemConsumable_NamelessVenom_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_NamelessVenom_Child.PrimalItemConsumable_NamelessVenom_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Narcotic.PrimalItemConsumable_Narcotic_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Narcotic_Child.PrimalItemConsumable_Narcotic_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMeat.PrimalItemConsumable_RawMeat_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_RawMeat_Child.PrimalItemConsumable_RawMeat_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMeat_Fish.PrimalItemConsumable_RawMeat_Fish_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_RawMeat_Fish_Child.PrimalItemConsumable_RawMeat_Fish_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMutton.PrimalItemConsumable_RawMutton_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_RawMutton_Child.PrimalItemConsumable_RawMutton_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawPrimeMeat.PrimalItemConsumable_RawPrimeMeat_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_RawPrimeMeat_Child.PrimalItemConsumable_RawPrimeMeat_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawPrimeMeat_Fish.PrimalItemConsumable_RawPrimeMeat_Fish_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_RawPrimeMeat_Fish_Child.PrimalItemConsumable_RawPrimeMeat_Fish_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SpoiledMeat.PrimalItemConsumable_SpoiledMeat_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_SpoiledMeat_Child.PrimalItemConsumable_SpoiledMeat_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Stimulant.PrimalItemConsumable_Stimulant_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Stimulant_Child.PrimalItemConsumable_Stimulant_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Citronal.PrimalItemConsumable_Veggie_Citronal_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Veggie_Citronal_Child.PrimalItemConsumable_Veggie_Citronal_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Longrass.PrimalItemConsumable_Veggie_Longrass_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Veggie_Longrass_Child.PrimalItemConsumable_Veggie_Longrass_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Rockarrot.PrimalItemConsumable_Veggie_Rockarrot_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Veggie_Rockarrot_Child.PrimalItemConsumable_Veggie_Rockarrot_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Savoroot.PrimalItemConsumable_Veggie_Savoroot_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_Veggie_Savoroot_Child.PrimalItemConsumable_Veggie_Savoroot_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumable_WyvernMilk.PrimalItemConsumable_WyvernMilk_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemConsumable_WyvernMilk_Child.PrimalItemConsumable_WyvernMilk_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemResource_CommonMushroom.PrimalItemResource_CommonMushroom_C", "/Game/Mods/Stack500_50/Consumables/PrimalItemResource_CommonMushroom_Child.PrimalItemResource_CommonMushroom_Child_C");
        referenceMapping.put("/Game/Genesis/Dinos/SpaceWhale/PrimalItemResource_Ambergris.PrimalItemResource_Ambergris_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Ambergris_Child.PrimalItemResource_Ambergris_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AmmoniteBlood.PrimalItemResource_AmmoniteBlood_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_AmmoniteBlood_Child.PrimalItemResource_AmmoniteBlood_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AnglerGel.PrimalItemResource_AnglerGel_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_AnglerGel_Child.PrimalItemResource_AnglerGel_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_BlackPearl.PrimalItemResource_BlackPearl_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_BlackPearl_Child.PrimalItemResource_BlackPearl_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_BlueSap.PrimalItemResource_BlueSap_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_BlueSap_Child.PrimalItemResource_BlueSap_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Charcoal.PrimalItemResource_Charcoal_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Charcoal_Child.PrimalItemResource_Charcoal_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinOrKeratin.PrimalItemResource_ChitinOrKeratin_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_ChitinOrKeratin_Child.PrimalItemResource_ChitinOrKeratin_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinPaste.PrimalItemResource_ChitinPaste_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_ChitinPaste_Child.PrimalItemResource_ChitinPaste_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Chitin.PrimalItemResource_Chitin_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Chitin_Child.PrimalItemResource_Chitin_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Clay.PrimalItemResource_Clay_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Clay_Child.PrimalItemResource_Clay_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CondensedGas.PrimalItemResource_CondensedGas_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_CondensedGas_Child.PrimalItemResource_CondensedGas_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CorruptedPolymer.PrimalItemResource_CorruptedPolymer_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_CorruptedPolymer_Child.PrimalItemResource_CorruptedPolymer_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CorruptedWood.PrimalItemResource_CorruptedWood_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_CorruptedWood_Child.PrimalItemResource_CorruptedWood_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Crystal.PrimalItemResource_Crystal_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Crystal_Child.PrimalItemResource_Crystal_Child_C");
        referenceMapping.put("/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalResources/Primal/PrimalItemResource_Crystal_IslesPrimal.PrimalItemResource_Crystal_IslesPrimal_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Crystal_IslesPrimal_Child.PrimalItemResource_Crystal_IslesPrimal_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Electronics.PrimalItemResource_Electronics_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Electronics_Child.PrimalItemResource_Electronics_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ElementOre.PrimalItemResource_ElementOre_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_ElementOre_Child.PrimalItemResource_ElementOre_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Element.PrimalItemResource_Element_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Element_Child.PrimalItemResource_Element_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Fibers.PrimalItemResource_Fibers_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Fibers_Child.PrimalItemResource_Fibers_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Flint.PrimalItemResource_Flint_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Flint_Child.PrimalItemResource_Flint_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_FracturedGem.PrimalItemResource_FracturedGem_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_FracturedGem_Child.PrimalItemResource_FracturedGem_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_FungalWood.PrimalItemResource_FungalWood_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_FungalWood_Child.PrimalItemResource_FungalWood_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Gasoline.PrimalItemResource_Gasoline_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gasoline_Child.PrimalItemResource_Gasoline_Child_C");
        referenceMapping.put("/Game/Mods/Stack500_50/Extinction/CoreBlueprints/Resources/PrimalItemResource_GasRefined.PrimalItemResource_GasRefined_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_GasRefined_Child.PrimalItemResource_Gas_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gas.PrimalItemResource_Gas_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gas_Child.PrimalItemResource_Gas_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_BioLum.PrimalItemResource_Gem_BioLum_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gem_BioLum_Child.PrimalItemResource_Gem_BioLum_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Element.PrimalItemResource_Gem_Element_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gem_Element_Child.PrimalItemResource_Gem_Element_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Fertile.PrimalItemResource_Gem_Fertile_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gem_Fertile_Child.PrimalItemResource_Gem_Fertile_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Gunpowder.PrimalItemResource_Gunpowder_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Gunpowder_Child.PrimalItemResource_Gunpowder_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Hair.PrimalItemResource_Hair_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Hair_Child.PrimalItemResource_Hair_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Hide.PrimalItemResource_Hide_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Hide_Child.PrimalItemResource_Hide_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Horn.PrimalItemResource_Horn_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Horn_Child.PrimalItemResource_Horn_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Keratin.PrimalItemResource_Keratin_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Keratin_Child.PrimalItemResource_Keratin_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_LeechBlood.PrimalItemResource_LeechBlood_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_LeechBlood_Child.PrimalItemResource_LeechBlood_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_MetalIngot.PrimalItemResource_MetalIngot_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_MetalIngot_Child.PrimalItemResource_MetalIngot_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Metal.PrimalItemResource_Metal_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Metal_Child.PrimalItemResource_Metal_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Obsidian.PrimalItemResource_Obsidian_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Obsidian_Child.PrimalItemResource_Obsidian_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Oil.PrimalItemResource_Oil_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Oil_Child.PrimalItemResource_Oil_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Pelt.PrimalItemResource_Pelt_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Pelt_Child.PrimalItemResource_Pelt_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer.PrimalItemResource_Polymer_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Polymer_Child.PrimalItemResource_Polymer_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer_Organic.PrimalItemResource_Polymer_Organic_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Polymer_Organic_Child.PrimalItemResource_Polymer_Organic_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_PreservingSalt.PrimalItemResource_PreservingSalt_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_PreservingSalt_Child.PrimalItemResource_PreservingSalt_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Propellant.PrimalItemResource_Propellant_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Propellant_Child.PrimalItemResource_Propellant_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareFlower.PrimalItemResource_RareFlower_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_RareFlower_Child.PrimalItemResource_RareFlower_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareMushroom.PrimalItemResource_RareMushroom_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_RareMushroom_Child.PrimalItemResource_RareMushroom_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_RawSalt.PrimalItemResource_RawSalt_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_RawSalt_Child.PrimalItemResource_RawSalt_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_RedSap.PrimalItemResource_RedSap_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_RedSap_Child.PrimalItemResource_RedSap_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Sand.PrimalItemResource_Sand_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Sand_Child.PrimalItemResource_Sand_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Sap.PrimalItemResource_Sap_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Sap_Child.PrimalItemResource_Sap_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ScrapMetalIngot.PrimalItemResource_ScrapMetalIngot_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_ScrapMetalIngot_Child.PrimalItemResource_ScrapMetalIngot_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ScrapMetal.PrimalItemResource_ScrapMetal_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_ScrapMetal_Child.PrimalItemResource_ScrapMetal_Child_C");
        referenceMapping.put("/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_Silicate.PrimalItemResource_Silicate_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Silicate_Child.PrimalItemResource_Silicate_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Silicon.PrimalItemResource_Silicon_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Silicon_Child.PrimalItemResource_Silicon_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Silk.PrimalItemResource_Silk_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Silk_Child.PrimalItemResource_Silk_Child_C");
        referenceMapping.put("/Game/PrimalEarth/Dinos/Achatina/PrimalItemResource_SnailPaste.PrimalItemResource_SnailPaste_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_SnailPaste_Child.PrimalItemResource_SnailPaste_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Sparkpowder.PrimalItemResource_Sparkpowder_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Sparkpowder_Child.PrimalItemResource_Sparkpowder_Child_C");
        referenceMapping.put("/Game/PrimalEarth/Dinos/Tusoteuthis/PrimalItemResource_SquidOil.PrimalItemResource_SquidOil_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_SquidOil_Child.PrimalItemResource_SquidOil_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Stone.PrimalItemResource_Stone_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Stone_Child.PrimalItemResource_Stone_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_SubstrateAbsorbent.PrimalItemResource_SubstrateAbsorbent_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_SubstrateAbsorbent_Child.PrimalItemResource_SubstrateAbsorbent_Child_C");
        referenceMapping.put("/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Sulfur.PrimalItemResource_Sulfur_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Sulfur_Child.PrimalItemResource_Sulfur_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Thatch.PrimalItemResource_Thatch_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Thatch_Child.PrimalItemResource_Thatch_Child_C");
        referenceMapping.put("/Game/Genesis/CoreBlueprints/Resources/PrimalItemResource_TurtleShell.PrimalItemResource_TurtleShell_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_TurtleShell_Child.PrimalItemResource_TurtleShell_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wood.PrimalItemResource_Wood_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Wood_Child.PrimalItemResource_Wood_Child_C");
        referenceMapping.put("/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wool.PrimalItemResource_Wool_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_Wool_Child.PrimalItemResource_Wool_Child_C");
        referenceMapping.put("/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_XenomorphPheromoneGland.PrimalItemResource_XenomorphPheromoneGland_C", "/Game/Mods/Stack500_50/Resources/PrimalItemResource_XenomorphPheromoneGland_Child.PrimalItemResource_XenomorphPheromoneGland_Child_C");
    }

    @Override
    public String getName() {
        return "MTSStackingMod";
    }

    @Override
    public Map<String, String> getMapping() {
        return MTSStackingMod.referenceMapping;
    }

}